// Quick AI Setup Script
console.log('🚀 AI Assistant Setup Guide');
console.log('==========================');
console.log('');
console.log('To get REAL AI responses from the network:');
console.log('');
console.log('1. Get FREE Gemini API Key:');
console.log('   → Go to: https://makersuite.google.com/app/apikey');
console.log('   → Sign in with Google account');
console.log('   → Click "Create API Key"');
console.log('   → Copy the key');
console.log('');
console.log('2. Create .env file in your project root:');
console.log('   → Create file: .env');
console.log('   → Add line: REACT_APP_GEMINI_API_KEY=your_actual_key_here');
console.log('');
console.log('3. Restart your app:');
console.log('   → Stop the app (Ctrl+C)');
console.log('   → Run: npm start');
console.log('');
console.log('4. Test with real questions:');
console.log('   → "What is the weather today?"');
console.log('   → "Tell me about Manchester United"');
console.log('   → "What is artificial intelligence?"');
console.log('');
console.log('✅ Your AI will then give REAL network responses!');
console.log('');
console.log('Optional: Get OpenAI key for even better responses:');
console.log('→ https://platform.openai.com/api-keys (requires payment)');